### ISSUE TITLE
2.3.0 TODO List

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#763]
- [x] 去掉任何 Ruby China 有关的字眼;
- [x] 去掉 Ruby China Only 的功能；
- [ ] 基于 Web 界面的初始化设置界面；
- [x] Docker 自动化部署方案，一键安装脚本；
- [x] 内建招聘、NoPoint 写死编号处理，同时兼容老数据；
- [x] 几个主要的大功能 (wiki,site,note,team,home) 可以配置启用/关闭；

**Comment by Eric-Guo** [comment]
我想请问现在ruby-china的部署也是使用docker了么？

**Comment by huacnlee** [comment]
还没有
Eric Guo <notifications@github.com>于2016年11月6日 周日下午12:00写道：
